name: CD

on:
  workflow_dispatch:
  push:
    # release unstable wont run if the commit is already a stable release (tagged commit)
    tags-ignore:
      - 'v*'
    branches:
      - main

jobs:
  release-unstable:
    # Don't run on any commit that features [skip ci] in the commit message
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    name: Publish unstable release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - name: Install
        run: npm install

      - name: Tests
        run: npm run test

      # We want to issue that all published versions never break the dashboard build
      - name: Build Dashboard
        run: npx lerna exec npm run build --scope @sidetree/dashboard

      - name: Setup npm profile
        run: |
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
          # Gives a clean failure prior to attempting a release if npm token is incorrect
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup git profile
        run: |
          git config user.name "Transmute CD"
          git config user.email "engineers@transmute.industries"

      - name: Publish unstable version with lerna
        run: npm run publish:unstable
